language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    include:
        - php: 5.4
          env:
              - DEPENDENCIES='low'
        - php: 5.5
        - php: 5.6
          env:
              - SYMFONY_VERSION=2.6.*
        - php: 5.6
          env:
              - SYMFONY_VERSION=2.7.*
        - php: 5.6
          env:
              - SYMFONY_VERSION=2.8.*
        - php: 5.6
        - php: 7.0
        - php: 7.1

before_install:
    - phpenv config-rm xdebug.ini || true
    - composer self-update
    - if [[ "$DEPENDENCIES" != "low" && ! $SYMFONY_VERSION ]]; then composer update; fi;
    - if [[ "$DEPENDENCIES" != "low" && $SYMFONY_VERSION ]]; then composer require symfony/symfony:${SYMFONY_VERSION} -n; fi;
    - if [[ "$DEPENDENCIES" == "low" ]]; then composer update --prefer-lowest; fi;

install:
    - wget http://selenium-release.storage.googleapis.com/2.50/selenium-server-standalone-2.50.1.jar

before_script:
    - php -S localhost:8080 -t features/fixtures/project/web > /dev/null 2>&1 &
    - sh -e /etc/init.d/xvfb start
    - export DISPLAY=:99.0
    - java -jar selenium-server-standalone-2.50.1.jar > /dev/null 2>&1 &
    - sleep 5
    - features/fixtures/project/app/console assets:install features/fixtures/project/web --relative --symlink

script:
    - ./bin/phpspec run --format=pretty
    - ./bin/behat --no-snippets --format=progress --profile=travis

notifications:
    irc: "irc.freenode.org#fsi-open"
