fsi_admin:
    path: /
    defaults:
        _controller: admin.controller.admin:indexAction

fsi_admin_locale:
    path: /locale/{_locale}
    defaults:
        _controller: admin.controller.admin:localeAction


fsi_admin_list:
    path: /list/{element}
    defaults:
        _controller: admin.controller.list:listAction

fsi_admin_form:
    path: /form/{element}/{id}
    defaults:
        _controller: admin.controller.form:formAction
        id: null

fsi_admin_batch:
    path: /batch/{element}
    defaults:
        _controller: admin.controller.batch:batchAction

fsi_admin_resource:
    path: /resource/{element}
    defaults:
        _controller: admin.controller.resource:resourceAction

fsi_admin_display:
    path: /display/{element}/{id}
    defaults:
        _controller: admin.controller.display:displayAction
